# Generated by Django 2.2.3 on 2019-08-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190813_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/basic-profile-img.png', upload_to='images/profile'),
        ),
    ]
