# Generated by Django 2.2.3 on 2019-08-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190813_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='introduce',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
