# Generated by Django 2.2.3 on 2019-08-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_introduce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='introduce',
        ),
    ]
