# Generated by Django 2.2.3 on 2019-08-21 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
