# Generated by Django 2.2.3 on 2019-08-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190813_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='animal', max_length=200),
        ),
    ]
